name="Nick Browser"

print(name.capitalize())
print(name.startswith("Ni"))
print(name.count('s'))
print(name.endswith("er"))
print(name.find('Ni'))
print(name.isalnum())
print(name.isalpha())
print(name.index('N'))
print(name.isidentifier())
print(name.isnumeric())
print(name.istitle())
print(name.isupper())
print(name.islower())
print(name.lower())
print(name.upper())
print(name.zfill(10))
print(name.splitlines())
print(name.swapcase())
print(name.rjust(13))
print(name.rpartition(' '))
print(name.replace('Browser','Castle '))
mytable= name.maketrans('N','V')
print(name.translate(mytable))
